{% set name = "hveto" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b5ab95c692682491b945b763990d599e80e78d69d638fe892bbe8a13f93856fd

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - gwdetchar >=1.1.0
    - gwpy >=2.0.0
    - gwtrigfind
    - lxml
    - MarkupPy >=1.14
    - matplotlib-base >=3.1
    - numpy >=1.10
    - python-ligo-lw >=1.5.0
    - scipy

test:
  requires:
    - flake8
    - pytest >=3.1.0
    - coverage
  imports:
    - hveto
    - hveto.config
    - hveto.const
    - hveto.core
    - hveto.html
    - hveto.plot
    - hveto.segments
    - hveto.triggers
    - hveto.tests
    - hveto.utils
  commands:
    # run unit tests
    - python -m pytest --pyargs {{ name }}
    # check that CLI modules run ok
    - python -m hveto --help
    - python -m hveto.cli.trace --help
    - python -m hveto.cli.cache_events --help

about:
  home: http://hveto.readthedocs.io
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A python implementation of the HierarchicalVeto (hveto) algorithm
  description: |
    This package provides a python implementation of the Hierarchichal Veto (hveto) algorithm

extra:
  recipe-maintainers:
    - alurban
    - duncanmmacleod
    - jrsmith02
