{% set name = "hveto" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed673e84e8fa293f78dd1ad214dd6c213c8035b03f65af5f83eba808dd3a5d6c

build:
  number: 1
  skip: true  # [win]
  skip: true  # [py2k]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python >=3.5
    - gwdetchar >=1.0.0
    - gwpy >=0.14.0
    - gwtrigfind
    - jinja2
    - lxml
    - MarkupPy >=1.14
    - matplotlib >=1.5
    - numpy >=1.10
    - pykerberos
    - scipy

test:
  requires:
    - flake8
    - pytest >=3.1.0
    - coverage
  imports:
    - hveto
    - hveto.config
    - hveto.core
    - hveto.html
    - hveto.plot
    - hveto.segments
    - hveto.triggers
    - hveto.tests
    - hveto.utils
  commands:
    # run unit tests
    - python -m pytest --pyargs {{ name }}
    # check that scripts run ok
    - hveto --help
    - hveto-trace --help
    - hveto-cache-events --help

about:
  home: http://hveto.readthedocs.io
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: A python implementation of the HierarchicalVeto (hveto) algorithm
  description: |
    This package provides a python implementation of the Hierarchichal Veto (hveto) algorithm

extra:
  recipe-maintainers:
    - alurban
    - duncanmmacleod
    - jrsmith02
