{% set name = "hveto" %}
{% set version = "2.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ecf7e0d56ebd09bcfb4d545d1f162ea6a0da1b931d43b4b21fbc7eecdca270dd

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - gwdetchar >=2.0.0
    - gwpy >=2.0.0
    - gwtrigfind
    - lxml
    - MarkupPy >=1.14
    - matplotlib-base >=3.1
    - numpy >=1.10
    - python-ligo-lw >=1.5.0
    - scipy

test:
  requires:
    - coverage
    - flake8
    - pytest >=3.1.0
    - python {{ python_min }}
  imports:
    - hveto
    - hveto.config
    - hveto.const
    - hveto.core
    - hveto.html
    - hveto.plot
    - hveto.segments
    - hveto.triggers
    - hveto.tests
    - hveto.utils
  commands:
    # run unit tests
    - python -m pytest --pyargs {{ name }}
    # check that CLI modules run ok
    - python -m hveto --help
    - python -m hveto.cli.cache_events --help
    - python -m hveto.cli.trace --help

about:
  home: http://hveto.readthedocs.io
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A python implementation of the HierarchicalVeto (hveto) algorithm
  description: |
    This package provides a python implementation of the Hierarchichal Veto (hveto) algorithm

extra:
  recipe-maintainers:
    - alurban
    - areeda
    - duncanmmacleod
    - eagoetz
    - jrsmith02
    - robertbruntz
