{% set name = "hveto" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 30d8fa78b6e00cd232e4ca620148744adfda7804cbf8cdf281de87e5732ea5b7

build:
  number: 0
  skip: true  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - jsmin
    - libsass
    - pip
    - python
    - setuptools
  run:
    - python >=2.7
    - dqsegdb
    - gitpython
    - gwdetchar
    - gwpy >=0.14.0
    - gwtrigfind
    - jinja2
    - lscsoft-glue >=2.0.0
    - lxml
    - matplotlib >=1.5
    - numpy >=1.10
    - pykerberos
    - scipy

test:
  requires:
    - pytest
    - mock  # [py<30]
  imports:
    - hveto
    - hveto.config
    - hveto.core
    - hveto.html
    - hveto.log
    - hveto.plot
    - hveto.segments
    - hveto.triggers
    - hveto.tests
    - hveto.utils
  commands:
    # run unit tests
    - python -m pytest --pyargs {{ name }}
    # check that scripts run ok
    - hveto --help
    - hveto-trace --help
    - hveto-cache-events --help

about:
  home: https://github.com/gwdetchar/hveto/
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: A python implementation of the HierarchicalVeto (hveto) algorithm
  description: |
    This package provides a python implementation of the Hierarchichal Veto (hveto) algorithm

extra:
  recipe-maintainers:
    - alurban
    - duncanmmacleod
    - jrsmith02
