{% set name = "hveto" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c45f5f7eb13b86d518896770dcfd530b3831cc4dc993f5cf08b7af04714f7c3d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - gwdetchar >=2.0.0
    - gwpy >=2.0.0
    - gwtrigfind
    - lxml
    - MarkupPy >=1.14
    - matplotlib-base >=3.1
    - numpy >=1.10
    - python-ligo-lw >=1.5.0
    - scipy

test:
  requires:
    - coverage
    - flake8
    - pytest >=3.1.0
  imports:
    - hveto
    - hveto.config
    - hveto.const
    - hveto.core
    - hveto.html
    - hveto.plot
    - hveto.segments
    - hveto.triggers
    - hveto.tests
    - hveto.utils
  commands:
    # run unit tests
    - python -m pytest --pyargs {{ name }}
    # check that CLI modules run ok
    - python -m hveto --help
    - python -m hveto.cli.cache_events --help
    - python -m hveto.cli.trace --help

about:
  home: http://hveto.readthedocs.io
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A python implementation of the HierarchicalVeto (hveto) algorithm
  description: |
    This package provides a python implementation of the Hierarchichal Veto (hveto) algorithm

extra:
  recipe-maintainers:
    - alurban
    - duncanmmacleod
    - jrsmith02
