{% set name = "hveto" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d2d56407039431d3f8c0d31aca6b91d4717c051393cac48b6cc24424d041d44

build:
  number: 0
  skip: true  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - jsmin
    - libsass
    - pip
    - python
    - setuptools
  run:
    - python >=2.7
    - gitpython
    - gwdetchar >=0.4.0
    - gwpy >=0.14.1
    - gwtrigfind
    - jinja2
    - lxml
    - MarkupPy >=1.14
    - matplotlib >=1.5
    - pathlib  # [py<30]
    - numpy >=1.10
    - pykerberos
    - scipy

test:
  requires:
    - pytest >=3.1.0
    - mock  # [py<30]
  imports:
    - hveto
    - hveto.config
    - hveto.core
    - hveto.html
    - hveto.plot
    - hveto.segments
    - hveto.triggers
    - hveto.tests
    - hveto.utils
  commands:
    # run unit tests
    - python -m pytest --pyargs {{ name }}
    # check that scripts run ok
    - hveto --help
    - hveto-trace --help
    - hveto-cache-events --help

about:
  home: https://github.com/gwdetchar/hveto/
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: A python implementation of the HierarchicalVeto (hveto) algorithm
  description: |
    This package provides a python implementation of the Hierarchichal Veto (hveto) algorithm

extra:
  recipe-maintainers:
    - alurban
    - duncanmmacleod
    - jrsmith02
