{% set name = "hveto" %}
{% set version = "2.1.9" %}

# 2.1.9 - compatibility with gwpy 4.0

# 2.1.9 - compatibility with gwpy 4.0

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b0ead71b43e3141a4cc29e5b06439b9ec3fc693c72dee5d9a498b827c198815c

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - gwdetchar >=2.3.2
    - gwpy >=2.0.0
    - gwtrigfind >=0.8.3
    - igwn-ligolw
    - lxml
    - MarkupPy >=1.14
    - matplotlib-base >=3.1
    - numpy >=2.0
    - igwn-ligolw
    - scipy

test:
  requires:
    - coverage
    - flake8
    - pytest >=3.1.0
    - python {{ python_min }}
  imports:
    - hveto
    - hveto.config
    - hveto.const
    - hveto.core
    - hveto.html
    - hveto.plot
    - hveto.segments
    - hveto.triggers
    - hveto.tests
    - hveto.utils
  commands:
    # run unit tests
    - python -m pytest --pyargs {{ name }}
    # check that CLI modules run ok
    - python -m hveto --help
    - python -m hveto.cli.cache_events --help
    - python -m hveto.cli.trace --help

about:
  home: http://hveto.readthedocs.io
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A python implementation of the HierarchicalVeto (hveto) algorithm
  description: |
    This package provides a python implementation of the Hierarchichal Veto (hveto) algorithm

extra:
  recipe-maintainers:
    - alurban
    - areeda
    - duncanmmacleod
    - eagoetz
    - jrsmith02
    - robertbruntz
