{% set name = "hveto" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c5bd29a7f1dc5d33887f4d93188d1a19962af9e9781e583a0ed846151055c96

build:
  number: 3
  skip: true  # [win]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - gwdetchar >=1.0.0
    - gwpy >=0.14.0
    - gwtrigfind
    - jinja2
    - lxml
    - MarkupPy >=1.14
    - matplotlib-base >=1.5
    - numpy >=1.10
    - pykerberos
    - scipy

test:
  requires:
    - flake8
    - pytest >=3.1.0
    - coverage
  imports:
    - hveto
    - hveto.config
    - hveto.core
    - hveto.html
    - hveto.plot
    - hveto.segments
    - hveto.triggers
    - hveto.tests
    - hveto.utils
  commands:
    # run unit tests
    - python -m pytest --pyargs {{ name }}
    # check that scripts run ok
    - hveto --help
    - hveto-trace --help
    - hveto-cache-events --help

about:
  home: http://hveto.readthedocs.io
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A python implementation of the HierarchicalVeto (hveto) algorithm
  description: |
    This package provides a python implementation of the Hierarchichal Veto (hveto) algorithm

extra:
  recipe-maintainers:
    - alurban
    - duncanmmacleod
    - jrsmith02
